version: '3.1'

volumes:
  logs:
    driver: local

services:
  mysql:
   image: mysql
   restart: always
   container_name: db-mysql
   ports:
    - 3307:3306
   environment:
     MYSQL_DATABASE: path
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   volumes:
    - ./db:/docker-entrypoint-initdb.d
  
   front:
    build: ./FRONT
    container_name: front
    ports: 
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3