version: '3.1'

volumes:
  logs:
    driver: local

services:
  mysql:
   image: mysql
   restart: always
   container_name: db-mysql
   ports:
    - 3307:3306
   environment:
     MYSQL_DATABASE: path
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: user
     MYSQL_PASSWORD: password
   volumes:
    - ./db:/docker-entrypoint-initdb.d

  back:
    build: ./node-back
    container_name: node-back
    ports: 
      - 3008:3008
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  front:
    build: ./react-front
    container_name: react-front
    ports: 
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3