# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code,
# and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build

on:
  push:
    branches: [ "develop", "feat/gitWorkflows" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node-back

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Print yarn and node versions
        run: |
          yarn --version
          node --version
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'node-back/yarn.lock'
      - name: Install react-scripts
        run: yarn add react-scripts@5.0.1
      - run: yarn

  frontend:

    runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./react-front

      strategy:
        matrix:
          node-version: [20.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
        - uses: actions/checkout@v3
        - name: Print yarn and node versions
          run: |
            yarn --version
            node --version
        - name: Use Node ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
            cache-dependency-path: 'react-front/yarn.lock'
        - name: Install react-scripts
          run: yarn add react-scripts@5.0.1
        - run: yarn
        - run: yarn build